version: "3"
services:
  web:
    build: .
    restart: on-failure
    env_file:
      - ./.env
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/www
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: "postgres:10.3-alpine"
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data