# Generated by Django 2.1.4 on 2018-12-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='address',
            field=models.CharField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(max_length=189),
        ),
        migrations.AlterField(
            model_name='listing',
            name='country',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='listing',
            name='name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='listing',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='website',
            field=models.URLField(max_length=254),
        ),
        migrations.AlterField(
            model_name='listing',
            name='zip_code',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(max_length=254),
        ),
    ]
