# Generated by Django 2.1.4 on 2018-12-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181221_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
